services:
  frontend:
    labels:
      - traefik.enable=true
      - traefik.http.services.loopjet-frappe.loadbalancer.server.port=8080
      - traefik.http.routers.loopjet-frappe.entrypoints=websecure
      - traefik.http.routers.loopjet-frappe.tls.certresolver=${TRAEFIK_CERTRESOLVER:-letsencrypt}
      - traefik.http.routers.loopjet-frappe.rule=${SITES_RULE:?SITES_RULE not set}

  mcp:
    labels:
      - traefik.enable=true
      - traefik.http.services.loopjet-frappe-mcp.loadbalancer.server.port=8000
      - traefik.http.routers.loopjet-frappe-mcp.entrypoints=websecure
      - traefik.http.routers.loopjet-frappe-mcp.tls.certresolver=${TRAEFIK_CERTRESOLVER:-letsencrypt}
      - traefik.http.routers.loopjet-frappe-mcp.rule=Host(`${MCP_SITE:-mcp.loopjet.io}`)
