services:
  configurator:
    image: ${CUSTOM_IMAGE}:${CUSTOM_TAG}
    platform: ${BUILD_PLATFORM:-linux/amd64}

  backend:
    image: ${CUSTOM_IMAGE}:${CUSTOM_TAG}
    platform: ${BUILD_PLATFORM:-linux/amd64}
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --header 'Host: ${ERP_SITE:-erp.localhost}' http://localhost:8000/api/method/ping >/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  frontend:
    image: ${CUSTOM_IMAGE}:${CUSTOM_TAG}
    platform: ${BUILD_PLATFORM:-linux/amd64}

  websocket:
    image: ${CUSTOM_IMAGE}:${CUSTOM_TAG}
    platform: ${BUILD_PLATFORM:-linux/amd64}

  queue-short:
    image: ${CUSTOM_IMAGE}:${CUSTOM_TAG}
    platform: ${BUILD_PLATFORM:-linux/amd64}

  queue-long:
    image: ${CUSTOM_IMAGE}:${CUSTOM_TAG}
    platform: ${BUILD_PLATFORM:-linux/amd64}

  scheduler:
    image: ${CUSTOM_IMAGE}:${CUSTOM_TAG}
    platform: ${BUILD_PLATFORM:-linux/amd64}
